import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1743551000000 implements MigrationInterface {
    name = 'InitialSchema1743551000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "email" character varying NOT NULL, "first_name" character varying, "middle_name" character varying, "last_name" character varying, "title" character varying, "designation" character varying, "password_hash" character varying NOT NULL, "role" character varying NOT NULL, "refresh_token_hash" character varying, "password_reset_token" character varying, "password_reset_expires_at" TIMESTAMP, "two_factor_enabled" boolean NOT NULL DEFAULT false, "two_factor_secret" text, "two_factor_temp_secret" text, "two_factor_temp_expires_at" TIMESTAMP, "two_factor_recovery_codes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_users_password_reset_token" ON "users" ("password_reset_token") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_04402eb4cf7be16f6cc5e5f078" ON "users" ("organization_id", "email") `);
        await queryRunner.query(`CREATE TABLE "groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "name" character varying NOT NULL, "description" text, "note" text, "parent_group_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_groups_org_parent" ON "groups" ("organization_id", "parent_group_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_08c715edd61042d4a5e05ed9f0" ON "groups" ("organization_id", "name") `);
        await queryRunner.query(`CREATE TABLE "contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "first_name" character varying, "middle_name" character varying, "last_name" character varying, "email" character varying, "phone" character varying, "gender" character varying, "student_id" character varying, "external_id" character varying, "guardian_name" character varying, "guardian_email" character varying, "guardian_phone" character varying, "password_hash" character varying, "is_active" boolean NOT NULL DEFAULT false, "must_reset_password" boolean NOT NULL DEFAULT true, "password_reset_token" character varying, "password_reset_expires_at" TIMESTAMP, "token_invalidated_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_contacts_password_reset_token" ON "contacts" ("password_reset_token") `);
        await queryRunner.query(`CREATE INDEX "IDX_contacts_org_created_at" ON "contacts" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4add4c3da31cc512f7dd525c47" ON "contacts" ("organization_id", "email") `);
        await queryRunner.query(`CREATE TABLE "form_fields" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "form_id" uuid NOT NULL, "label" character varying NOT NULL, "type" character varying NOT NULL, "required" boolean NOT NULL DEFAULT false, "options" json, "order_index" integer NOT NULL, "validation_rules" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dc4b73290f2926c3a7d7c92d1e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d5d1ce3d82c2d92cb6ecd1f4db" ON "form_fields" ("form_id", "order_index") `);
        await queryRunner.query(`CREATE TABLE "form_targets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "form_id" uuid NOT NULL, "target_type" character varying NOT NULL, "target_id" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9655f31e46d4b9ef1fb7f16cf00" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_970b0f3d9e64a5c00201bf4eb1" ON "form_targets" ("form_id", "target_type", "target_id") `);
        await queryRunner.query(`CREATE TABLE "forms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "title" character varying NOT NULL, "category" character varying, "description" text, "note" text, "slug" character varying NOT NULL, "payment_type" character varying NOT NULL DEFAULT 'FIXED', "amount" numeric(10,2), "access_mode" character varying NOT NULL DEFAULT 'OPEN', "identity_validation_mode" character varying NOT NULL DEFAULT 'NONE', "identity_field_label" character varying, "allow_partial" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba062fd30b06814a60756f233da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_forms_org_is_active" ON "forms" ("organization_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_forms_org_created_at" ON "forms" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_aaaf998d618db25bf306d5fc92" ON "forms" ("organization_id", "slug") `);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "user_id" uuid, "contact_id" uuid, "action" character varying NOT NULL, "entity_type" character varying NOT NULL, "entity_id" character varying NOT NULL, "metadata" json, "ip_address" character varying, "user_agent" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_38c8807aac79cec33e3f55098a" ON "activity_logs" ("organization_id", "user_agent") `);
        await queryRunner.query(`CREATE INDEX "IDX_16b06e4b141c361c60e7bfbb83" ON "activity_logs" ("organization_id", "ip_address") `);
        await queryRunner.query(`CREATE INDEX "IDX_a78aef7d92c030d5c80583875c" ON "activity_logs" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "submission_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "reference" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "total_amount" numeric(10,2), "amount_paid" numeric(10,2) NOT NULL DEFAULT '0', "balance_due" numeric(10,2) NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'PENDING', "payment_method" character varying NOT NULL DEFAULT 'ONLINE', "confirmed_at" TIMESTAMP, "confirmed_by_user_id" uuid, "confirmation_note" text, "external_reference" character varying, "paid_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_payments_org_created_at" ON "payments" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_47759d1f579965d1930cb53db5" ON "payments" ("organization_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0a497b6d14b7e8323a87d10ab9" ON "payments" ("organization_id", "reference") `);
        await queryRunner.query(`CREATE TABLE "payment_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payment_id" uuid NOT NULL, "event_id" character varying NOT NULL, "organization_id" uuid NOT NULL, "event" character varying NOT NULL, "payload" json NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b5bda25324e539ea41bc09697f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d489f934365435277bd0c69ac1" ON "payment_logs" ("payment_id", "event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_39d3c22899a51516e6aa584131" ON "payment_logs" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "email_verified" boolean NOT NULL DEFAULT false, "email_verification_token" character varying, "email_verification_expires_at" TIMESTAMP, "paystack_public_key" character varying, "paystack_secret_key" character varying, "paystack_webhook_url" character varying, "logo_url" character varying, "subdomain" character varying, "custom_domain" character varying, "require_contact_login" boolean NOT NULL DEFAULT false, "notify_submission_confirmation" boolean NOT NULL DEFAULT true, "notify_payment_confirmation" boolean NOT NULL DEFAULT true, "notify_payment_failure" boolean NOT NULL DEFAULT true, "partial_payment_limit" numeric(10,2), "enabled_payment_methods" character varying array NOT NULL DEFAULT ARRAY['ONLINE']::varchar[], "market_readiness_flags" jsonb NOT NULL DEFAULT '{}'::jsonb, "billing_plan_tier" character varying NOT NULL DEFAULT 'free', "data_retention_contact_days" integer DEFAULT '1095', "data_retention_submission_days" integer DEFAULT '2555', "data_retention_audit_days" integer DEFAULT '2555', "auto_purge_retention_enabled" boolean NOT NULL DEFAULT true, "last_data_retention_purge_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_organizations_custom_domain_unique" ON "organizations" ("custom_domain") WHERE "custom_domain" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_organizations_subdomain_unique" ON "organizations" ("subdomain") WHERE "subdomain" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_org_email_verification_token" ON "organizations" ("email_verification_token") `);
        await queryRunner.query(`CREATE TABLE "submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "form_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "contact_id" uuid, "data" json NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_10b3be95b8b2fb1e482e07d706b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_submissions_org_created_at" ON "submissions" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_submissions_org_contact" ON "submissions" ("organization_id", "contact_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_280277d68b3b00d69582a2bebd" ON "submissions" ("organization_id", "form_id") `);
        await queryRunner.query(`CREATE TABLE "internal_notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "created_by_user_id" uuid, "title" character varying NOT NULL, "body" text NOT NULL, "audience_type" character varying NOT NULL DEFAULT 'ALL_USERS', "target_user_ids" uuid array, "read_by_user_ids" uuid array NOT NULL DEFAULT ARRAY[]::uuid[], "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_709cef32600e92750d14a6c177d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_internal_notifications_org_created_at" ON "internal_notifications" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "contact_notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "created_by_user_id" uuid, "title" character varying NOT NULL, "body" text NOT NULL, "type" character varying NOT NULL DEFAULT 'GENERAL', "audience_type" character varying NOT NULL DEFAULT 'ALL_CONTACTS', "target_contact_ids" uuid array, "read_by_contact_ids" uuid array NOT NULL DEFAULT ARRAY[]::uuid[], "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_53747d53e699c8cc80836763368" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_contact_notifications_org_created_at" ON "contact_notifications" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "reconciliation_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "period_start" date NOT NULL, "period_end" date NOT NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "summary" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4edbdb165c9e754997036a4176a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_reconciliation_runs_org_created" ON "reconciliation_runs" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "reconciliation_exceptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "run_id" uuid NOT NULL, "payment_id" uuid, "reference" character varying, "type" character varying NOT NULL, "severity" character varying NOT NULL DEFAULT 'MEDIUM', "status" character varying NOT NULL DEFAULT 'OPEN', "details" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d1cdb3833631e18e1dd635895e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_reconciliation_exceptions_org_created" ON "reconciliation_exceptions" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_reconciliation_exceptions_run_status" ON "reconciliation_exceptions" ("run_id", "status") `);
        await queryRunner.query(`CREATE TABLE "payment_recovery_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "candidate_id" uuid, "event_type" character varying NOT NULL, "payload" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_81d7500653d5c094457ad103bf2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_payment_recovery_events_candidate_created" ON "payment_recovery_events" ("candidate_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "payment_recovery_candidates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "payment_id" uuid NOT NULL, "reference" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'OPEN', "last_notified_at" TIMESTAMP, "attempt_count" integer NOT NULL DEFAULT '0', "metadata" jsonb, "detected_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_afb36fe3b26be75908831887b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_payment_recovery_candidates_payment" ON "payment_recovery_candidates" ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payment_recovery_candidates_org_status" ON "payment_recovery_candidates" ("organization_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payment_recovery_candidates_org_detected" ON "payment_recovery_candidates" ("organization_id", "detected_at") `);
        await queryRunner.query(`CREATE TABLE "partners" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "name" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'ACTIVE', "config" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_998645b20820e4ab99aeae03b41" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_partners_org_created" ON "partners" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "partner_tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "partner_id" uuid NOT NULL, "tenant_organization_id" uuid NOT NULL, "onboarding_status" character varying NOT NULL DEFAULT 'PENDING', "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a6a60dbfb7541604bf4e41565ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_partner_tenants_partner_tenant_org" ON "partner_tenants" ("partner_id", "tenant_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_partner_tenants_org_status" ON "partner_tenants" ("organization_id", "onboarding_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_partner_tenants_partner_created" ON "partner_tenants" ("partner_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "integration_endpoints" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "type" character varying NOT NULL, "target" character varying NOT NULL, "secret" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, "config" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3e512fe7ce9fe22bf520a046a2a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_integration_endpoints_org_active" ON "integration_endpoints" ("organization_id", "active") `);
        await queryRunner.query(`CREATE TABLE "integration_deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "endpoint_id" uuid NOT NULL, "event_type" character varying NOT NULL, "payload_hash" character varying(128) NOT NULL, "status" character varying NOT NULL DEFAULT 'QUEUED', "attempts" integer NOT NULL DEFAULT '0', "last_error" text, "delivered_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d8ccb7a6e471cdb4ec5a3972ed6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_integration_deliveries_org_status" ON "integration_deliveries" ("organization_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_integration_deliveries_endpoint_created" ON "integration_deliveries" ("endpoint_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "installment_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "form_id" uuid NOT NULL, "name" character varying NOT NULL, "currency" character varying NOT NULL DEFAULT 'NGN', "total_amount" numeric(10,2) NOT NULL, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2bcdae2e05a4584743ee0d991db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_installment_plans_org_form" ON "installment_plans" ("organization_id", "form_id") `);
        await queryRunner.query(`CREATE TABLE "installment_plan_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plan_id" uuid NOT NULL, "label" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "due_date" date NOT NULL, "penalty_rule" jsonb, "order_index" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_fe31ab07758aea407767c9954e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_installment_plan_items_plan_order" ON "installment_plan_items" ("plan_id", "order_index") `);
        await queryRunner.query(`CREATE TABLE "dunning_campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "status" character varying(50) NOT NULL DEFAULT 'DRAFT', "min_days_overdue" integer NOT NULL DEFAULT '7', "max_days_overdue" integer NOT NULL DEFAULT '365', "min_outstanding_amount" numeric(19,4) NOT NULL DEFAULT '0', "escalation_rules" jsonb NOT NULL DEFAULT '{}', "filter_criteria" jsonb NOT NULL DEFAULT '{}', "execution_frequency" character varying(50) NOT NULL DEFAULT 'MANUAL', "total_runs" integer NOT NULL DEFAULT '0', "total_outstanding_snapshot" numeric(19,4), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "last_executed_at" TIMESTAMP, CONSTRAINT "PK_72ac472a57144917f1d06f7e4d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "arrears_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "run_id" uuid NOT NULL, "contact_id" uuid NOT NULL, "outstanding_amount" numeric(19,4) NOT NULL, "days_overdue" integer NOT NULL, "current_stage" integer NOT NULL DEFAULT '0', "status" character varying(50) NOT NULL DEFAULT 'NOT_STARTED', "delinquency_start_date" TIMESTAMP, "metadata" jsonb NOT NULL DEFAULT '{}', "captured_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e0dfb086201b6559438c686b84b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dunning_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "campaign_id" uuid NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'SCHEDULED', "scheduled_for" TIMESTAMP, "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "contacts_evaluated" integer NOT NULL DEFAULT '0', "contacts_escalated" integer NOT NULL DEFAULT '0', "notifications_sent" integer NOT NULL DEFAULT '0', "total_outstanding" numeric(19,4) NOT NULL DEFAULT '0', "summary" jsonb NOT NULL DEFAULT '{}', "error_message" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fc9a3ab7dfd15bc3a58f189b40a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contact_installment_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "contact_id" uuid NOT NULL, "plan_id" uuid NOT NULL, "outstanding_amount" numeric(10,2) NOT NULL, "status" character varying NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e0062eb2eafcf85c4694ce69bbc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_contact_installment_accounts_contact_plan" ON "contact_installment_accounts" ("contact_id", "plan_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_contact_installment_accounts_org_contact" ON "contact_installment_accounts" ("organization_id", "contact_id") `);
        await queryRunner.query(`CREATE TABLE "compliance_export_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "requested_by_user_id" uuid NOT NULL, "status" character varying NOT NULL DEFAULT 'QUEUED', "scope" jsonb, "request_reason" text, "completed_at" TIMESTAMP, "download_url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_76f15113aa3bab988fa0919982e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_compliance_export_jobs_org_status" ON "compliance_export_jobs" ("organization_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_compliance_export_jobs_org_created" ON "compliance_export_jobs" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "compliance_export_artifacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "job_id" uuid NOT NULL, "artifact_type" character varying NOT NULL, "file_path" character varying NOT NULL, "checksum" character varying, "size_bytes" bigint, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5d0861afb546a985f5c3858f670" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_compliance_export_artifacts_org_type" ON "compliance_export_artifacts" ("organization_id", "artifact_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_compliance_export_artifacts_job_created" ON "compliance_export_artifacts" ("job_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "checkout_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "form_id" uuid, "contact_id" uuid, "reference" character varying, "status" character varying NOT NULL DEFAULT 'STARTED', "completed_at" TIMESTAMP, "metadata" jsonb, "started_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5730b2bbc190203a94941d82bd1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_checkout_sessions_org_status" ON "checkout_sessions" ("organization_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_checkout_sessions_org_started" ON "checkout_sessions" ("organization_id", "started_at") `);
        await queryRunner.query(`CREATE TABLE "contact_imports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by" character varying, "status" character varying NOT NULL DEFAULT 'PENDING', "total_count" integer NOT NULL DEFAULT '0', "success_count" integer NOT NULL DEFAULT '0', "failure_count" integer NOT NULL DEFAULT '0', "payload" json, "errors" json, "completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4297d9cdb758eea151bbb09dddb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_89be8060dca205bc537069258c" ON "contact_imports" ("organization_id", "status") `);
        await queryRunner.query(`CREATE TABLE "invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "email" character varying NOT NULL, "first_name" character varying, "last_name" character varying, "title" character varying, "designation" character varying, "role" character varying NOT NULL DEFAULT 'STAFF', "token" character varying NOT NULL, "invited_by" character varying, "accepted" boolean NOT NULL DEFAULT false, "accepted_at" TIMESTAMP, "expires_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5dec98cfdfd562e4ad3648bbb07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3afc80b5ecc0276428da3e3a87" ON "invitations" ("organization_id", "email") `);
        await queryRunner.query(`CREATE TABLE "contact_groups" ("contact_id" uuid NOT NULL, "group_id" uuid NOT NULL, CONSTRAINT "PK_2f3bd4c833cae425af7a121b11d" PRIMARY KEY ("contact_id", "group_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_42ed359c818642df3a66050cc4" ON "contact_groups" ("contact_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0415124bdeeab55adabece2a3d" ON "contact_groups" ("group_id") `);
        await queryRunner.query(`CREATE TABLE "form_groups" ("form_id" uuid NOT NULL, "group_id" uuid NOT NULL, CONSTRAINT "PK_2b2de2a865883fd1a88817ce08f" PRIMARY KEY ("form_id", "group_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bea72a8467067cd5d20c8f7074" ON "form_groups" ("form_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a55b4e618374f8d9fa9376815" ON "form_groups" ("group_id") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_21a659804ed7bf61eb91688dea7" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_f7f1b335edff519132aa2163fef" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_d36341a361a4d382b6ce3e66a3c" FOREIGN KEY ("parent_group_id") REFERENCES "groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_0799185e89f0eec8f7ec05a5bb8" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "FK_c2076d2b47add1aaa07608e0cf2" FOREIGN KEY ("form_id") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_targets" ADD CONSTRAINT "FK_4eaf30670a57a2f61196262eebe" FOREIGN KEY ("form_id") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forms" ADD CONSTRAINT "FK_01c3de6bd8ad61f157ea09b48d5" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_f2a5695f730cbe9bf16eeb74342" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_d54f841fa5478e4734590d44036" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_aff056d57b44308d7105abdacab" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_fc07ace491143726974991711f2" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_37b088b5283003b89147927b1dc" FOREIGN KEY ("submission_id") REFERENCES "submissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_logs" ADD CONSTRAINT "FK_2c4b13396a8eba5b19a281306a9" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_logs" ADD CONSTRAINT "FK_6508afaa58d3f3e97c347631c0c" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_10cf656e6b0cf503a9d4a6bfbe6" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_b47e4895139bd0165ddfe9fa1aa" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dunning_campaigns" ADD CONSTRAINT "FK_64612f675f3eedac06123a44aaf" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arrears_snapshots" ADD CONSTRAINT "FK_b441f2c5bd77189dedb61a3bf39" FOREIGN KEY ("run_id") REFERENCES "dunning_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arrears_snapshots" ADD CONSTRAINT "FK_fe6ab04e3ba3cf435e2729a9de8" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dunning_runs" ADD CONSTRAINT "FK_e70f689f0fe4adae0c78b445a49" FOREIGN KEY ("campaign_id") REFERENCES "dunning_campaigns"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_imports" ADD CONSTRAINT "FK_41d59f59ba2e2d56e435eb97d52" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_42d1dbb4d85dc3643fdc6560af0" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_groups" ADD CONSTRAINT "FK_42ed359c818642df3a66050cc4e" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "contact_groups" ADD CONSTRAINT "FK_0415124bdeeab55adabece2a3d0" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_groups" ADD CONSTRAINT "FK_bea72a8467067cd5d20c8f70740" FOREIGN KEY ("form_id") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "form_groups" ADD CONSTRAINT "FK_1a55b4e618374f8d9fa9376815e" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "form_groups" DROP CONSTRAINT "FK_1a55b4e618374f8d9fa9376815e"`);
        await queryRunner.query(`ALTER TABLE "form_groups" DROP CONSTRAINT "FK_bea72a8467067cd5d20c8f70740"`);
        await queryRunner.query(`ALTER TABLE "contact_groups" DROP CONSTRAINT "FK_0415124bdeeab55adabece2a3d0"`);
        await queryRunner.query(`ALTER TABLE "contact_groups" DROP CONSTRAINT "FK_42ed359c818642df3a66050cc4e"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_42d1dbb4d85dc3643fdc6560af0"`);
        await queryRunner.query(`ALTER TABLE "contact_imports" DROP CONSTRAINT "FK_41d59f59ba2e2d56e435eb97d52"`);
        await queryRunner.query(`ALTER TABLE "dunning_runs" DROP CONSTRAINT "FK_e70f689f0fe4adae0c78b445a49"`);
        await queryRunner.query(`ALTER TABLE "arrears_snapshots" DROP CONSTRAINT "FK_fe6ab04e3ba3cf435e2729a9de8"`);
        await queryRunner.query(`ALTER TABLE "arrears_snapshots" DROP CONSTRAINT "FK_b441f2c5bd77189dedb61a3bf39"`);
        await queryRunner.query(`ALTER TABLE "dunning_campaigns" DROP CONSTRAINT "FK_64612f675f3eedac06123a44aaf"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_b47e4895139bd0165ddfe9fa1aa"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_10cf656e6b0cf503a9d4a6bfbe6"`);
        await queryRunner.query(`ALTER TABLE "payment_logs" DROP CONSTRAINT "FK_6508afaa58d3f3e97c347631c0c"`);
        await queryRunner.query(`ALTER TABLE "payment_logs" DROP CONSTRAINT "FK_2c4b13396a8eba5b19a281306a9"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_37b088b5283003b89147927b1dc"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_fc07ace491143726974991711f2"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_aff056d57b44308d7105abdacab"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_d54f841fa5478e4734590d44036"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_f2a5695f730cbe9bf16eeb74342"`);
        await queryRunner.query(`ALTER TABLE "forms" DROP CONSTRAINT "FK_01c3de6bd8ad61f157ea09b48d5"`);
        await queryRunner.query(`ALTER TABLE "form_targets" DROP CONSTRAINT "FK_4eaf30670a57a2f61196262eebe"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "FK_c2076d2b47add1aaa07608e0cf2"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_0799185e89f0eec8f7ec05a5bb8"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_d36341a361a4d382b6ce3e66a3c"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_f7f1b335edff519132aa2163fef"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_21a659804ed7bf61eb91688dea7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a55b4e618374f8d9fa9376815"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bea72a8467067cd5d20c8f7074"`);
        await queryRunner.query(`DROP TABLE "form_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0415124bdeeab55adabece2a3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42ed359c818642df3a66050cc4"`);
        await queryRunner.query(`DROP TABLE "contact_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3afc80b5ecc0276428da3e3a87"`);
        await queryRunner.query(`DROP TABLE "invitations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89be8060dca205bc537069258c"`);
        await queryRunner.query(`DROP TABLE "contact_imports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_checkout_sessions_org_started"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_checkout_sessions_org_status"`);
        await queryRunner.query(`DROP TABLE "checkout_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_compliance_export_artifacts_job_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_compliance_export_artifacts_org_type"`);
        await queryRunner.query(`DROP TABLE "compliance_export_artifacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_compliance_export_jobs_org_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_compliance_export_jobs_org_status"`);
        await queryRunner.query(`DROP TABLE "compliance_export_jobs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_contact_installment_accounts_org_contact"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_contact_installment_accounts_contact_plan"`);
        await queryRunner.query(`DROP TABLE "contact_installment_accounts"`);
        await queryRunner.query(`DROP TABLE "dunning_runs"`);
        await queryRunner.query(`DROP TABLE "arrears_snapshots"`);
        await queryRunner.query(`DROP TABLE "dunning_campaigns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_installment_plan_items_plan_order"`);
        await queryRunner.query(`DROP TABLE "installment_plan_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_installment_plans_org_form"`);
        await queryRunner.query(`DROP TABLE "installment_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_integration_deliveries_endpoint_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_integration_deliveries_org_status"`);
        await queryRunner.query(`DROP TABLE "integration_deliveries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_integration_endpoints_org_active"`);
        await queryRunner.query(`DROP TABLE "integration_endpoints"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_partner_tenants_partner_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_partner_tenants_org_status"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_partner_tenants_partner_tenant_org"`);
        await queryRunner.query(`DROP TABLE "partner_tenants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_partners_org_created"`);
        await queryRunner.query(`DROP TABLE "partners"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payment_recovery_candidates_org_detected"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payment_recovery_candidates_org_status"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_payment_recovery_candidates_payment"`);
        await queryRunner.query(`DROP TABLE "payment_recovery_candidates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payment_recovery_events_candidate_created"`);
        await queryRunner.query(`DROP TABLE "payment_recovery_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reconciliation_exceptions_run_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reconciliation_exceptions_org_created"`);
        await queryRunner.query(`DROP TABLE "reconciliation_exceptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reconciliation_runs_org_created"`);
        await queryRunner.query(`DROP TABLE "reconciliation_runs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_contact_notifications_org_created_at"`);
        await queryRunner.query(`DROP TABLE "contact_notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_internal_notifications_org_created_at"`);
        await queryRunner.query(`DROP TABLE "internal_notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_280277d68b3b00d69582a2bebd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_submissions_org_contact"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_submissions_org_created_at"`);
        await queryRunner.query(`DROP TABLE "submissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_org_email_verification_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_organizations_subdomain_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_organizations_custom_domain_unique"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39d3c22899a51516e6aa584131"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d489f934365435277bd0c69ac1"`);
        await queryRunner.query(`DROP TABLE "payment_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a497b6d14b7e8323a87d10ab9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47759d1f579965d1930cb53db5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_org_created_at"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a78aef7d92c030d5c80583875c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16b06e4b141c361c60e7bfbb83"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38c8807aac79cec33e3f55098a"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aaaf998d618db25bf306d5fc92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_forms_org_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_forms_org_is_active"`);
        await queryRunner.query(`DROP TABLE "forms"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_970b0f3d9e64a5c00201bf4eb1"`);
        await queryRunner.query(`DROP TABLE "form_targets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5d1ce3d82c2d92cb6ecd1f4db"`);
        await queryRunner.query(`DROP TABLE "form_fields"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4add4c3da31cc512f7dd525c47"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_contacts_org_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_contacts_password_reset_token"`);
        await queryRunner.query(`DROP TABLE "contacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08c715edd61042d4a5e05ed9f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_groups_org_parent"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04402eb4cf7be16f6cc5e5f078"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_password_reset_token"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
