services:
  - type: web
    name: payforms-backend
    env: node
    plan: free
    branch: main
    rootDir: apps/backend
    buildCommand: npm install --include=dev && npx tsc -p tsconfig.prod.json
    startCommand: npm run migration:run:prod && npm run start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TENANT_BASE_DOMAIN
        value: payforms.com.ng
